export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const FETCH_POKEMON_LIST = 'pokemonReducer/FETCH_POKEMON_LIST';
export const FETCH_POKEMON_LIST_SUCCESS =
  'pokemonReducer/FETCH_POKEMON_LIST_SUCCESS';
export const FETCH_POKEMON_LIST_ERROR =
  'pokemonReducer/FETCH_POKEMON_LIST_ERROR';

export const FETCH_POKEMON_DETAILS = 'pokemon/FETCH_POKEMON_DETAILS';
export const FETCH_POKEMON_DETAILS_SUCCESS = 'pokemon/FETCH_POKEMON_DETAILS_SUCCESS';
export const FETCH_POKEMON_DETAILS_ERROR = 'pokemon/FETCH_POKEMON_DETAILS_ERROR';

